config/routes.rb
Trust::Application.routes.draw do
  resources :isms
  
  root :to => 'isms#new'
  
  match '/edit', :to => 'isms#edit'
  match '/index', :to => 'isms#index'
  match '/man', :to =>'isms#new'
  match '/woman', :to =>'isms#new', :defaults => {:woman => true}
  match '/success', :to => "isms#success", :as => :success

end

app/models/ism.rb
class Ism < ActiveRecord::Base
  MAN = "man"
  WOMAN = "woman"
  
  validates :description, :gender, :category, :presence => true
  validates :description, :length => { :maximum => 140 }
  validates :description, :uniqueness => true
  
  def self.random(conditions = {})
    ism_count = Ism.where(conditions).count
    Ism.where(conditions).first(:offset => rand(ism_count))
  end
  
  def woman?
    self.gender == WOMAN
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/isms_controller.rb
class IsmsController < ApplicationController
  
  before_filter :set_gender
  
  def index
    @isms = Ism.all

    respond_to do |format|
      format.html
    end
  end
  
  def show
    @ism = Ism.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
  
  def new
    @ism = Ism.new
    @fetch = Ism.random(:gender => @gender)

    respond_to do |format|
      format.html
    end
  end
  
  def edit
    @ism = Ism.find(params[:id])
  end

  def create
    @ism = Ism.new(params[:ism])

    respond_to do |format|
      if @ism.save
        format.html { redirect_to(success_path(:woman => @ism.woman?)) }
      else
        format.html { 
            @fetch = Ism.random
            render :action => "new" 
        }
      end
    end
  end

  def update
    @ism = Ism.find(params[:id])

    respond_to do |format|
      if @ism.update_attributes(params[:ism])
        format.html { redirect_to(@ism, :notice => 'Ism was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @ism = Ism.find(params[:id])
    @ism.destroy

    respond_to do |format|
      format.html { redirect_to(isms_url) }
    end
  end
  
  def success
  
  end

  private
  
  def set_gender
    @gender = params[:woman] ? Ism::WOMAN : Ism::MAN
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/isms_helper.rb
module IsmsHelper

end

app/views/isms/_form.html.erb
<%= form_for(@ism) do |f| %>

            <fieldset id="submit">
                <ul>
                    <li class="status">
                        <label for="gender">Gender:</label>
                        <ul>
                            <li><%= radio_button("ism", "gender", Ism::MAN) %>Man</li>
                            <li><%= radio_button("ism", "gender", Ism::WOMAN) %>Woman</li>
                        </ul>
                    </li>
                    <li class="error"></li>
                    <li class="status">
                        <label for="category">Category:</label>
                        <ul>
                            <li><%= radio_button("ism", "category", "Music") %>Music</li>
                            <li><%= radio_button("ism", "category", "Sports") %>Sports</li>
                            <li><%= radio_button("ism", "category", "Food & Drink") %>Food & Drink</li>
                            <li><%= radio_button("ism", "category", "Health") %>Health</li>
                            <li><%= radio_button("ism", "category", "Fashion") %>Fashion</li>
                            <li><%= radio_button("ism", "category", "Miscellaneous") %>Miscellaneous</li>
                        </ul>
                    </li>
                    <li class="error"></li>
                    <li class="status">
                        <label for="description" id="textarea-label">Never Trust a <%= @gender.capitalize %> Who...</label>
                        <%= f.text_area :description, :cols => "4", :rows => "4" %>
                    </li>
                    <li class="error"></li>
                    <li class="warning yes"></li>
                    <li>
                        <%= f.submit "Submit" %>
                    </li>
                </ul>
            </fieldset>
<% end %>

app/views/isms/edit.html.erb
<%= render 'form' %>

app/views/isms/index.html.erb
<h1>-isms</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Gender</th>
    <th>Category</th>
    <th></th>
    <th></th>
  </tr>

<% @isms.each do |ism| %>
  <tr>
    <td><%= ism.description %></td>
    <td><%= ism.gender %></td>
    <td><%= ism.category %></td>
    <td><%= link_to 'Edit', edit_ism_path(ism) %></td>
    <td><%= link_to 'Destroy', ism, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/isms/new.html.erb
<h1>Never Trust a <%= @gender.capitalize %> Who <%= @fetch.description %></h1>

<div id="submit-box">
    <a href="#" title="Submit your own" id="add">Submit your own</a>
    <h2>Submit your own.</h2>
    <p>Maybe we'll post it. Maybe we won't.</p>
</div>

<%= render 'form' %>

<script type="text/javascript">
$(document).ready(function(){
    $("#submit").hide();
    $("#submit-box a").click(function(){
        $("#submit-box a").toggleClass("toggle");
        $("#submit").slideToggle("fast");
        return false;
    });

});
</script>

app/views/isms/show.html.erb
<div id="notice">
    <h2><%= notice %></h2>
</div>

<%= render 'form' %>

app/views/isms/success.html.erb
<div id="submit-box">
    <img src="images/received.gif" alt="Submission recieved" width="38" height="46" id="received" />
    <h2>Submission received.</h2>
    <p>If it was cool, you'll see it on the site.</p>
</div>

app/views/layouts/_form.html.erb
<%= form_for(@ism) do |f| %>

            <fieldset id="submit">
                <ul>
                    <li class="check-mark">
                        <label for="gender">Gender:</label>
                        <ul>
                            <li><%= radio_button("ism", "gender", "Man") %><%= "Man" %></li>
                            <li><%= radio_button("ism", "gender", "Woman") %><%= "Woman" %></li>
                        </ul>
                    </li>
                    <li class="check-mark">
                        <label for="category">Category:</label>
                        <ul>
                            <li><%= radio_button("ism", "category", "Music") %><%= "Music" %></li>
                            <li><%= radio_button("ism", "category", "Sports") %><%= "Sports" %></li>
                            <li><%= radio_button("ism", "category", "Food & Drink") %><%= "Food & Drink" %></li>
                            <li><%= radio_button("ism", "category", "Health") %><%= "Health" %></li>
                            <li><%= radio_button("ism", "category", "Fashion") %><%= "Fashion" %></li>
                            <li><%= radio_button("ism", "category", "Miscellaneous") %><%= "Miscellaneous" %></li>
                        </ul>
                    </li>
                    <li class="check-mark">
                        <%= f.text_field :description %>
                    </li>
                    <li id="alert-wrap">
                        <p id="alert-message">Not yet! Make sure you see all 3 check marks before you hit "submit."</p>
                    </li>
                    <li>
                        <%= f.submit "Submit" %>
                    </li>
                </ul>
            </fieldset>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "Never trust a...", root_path, :title => "Show me more", :id => "refresh" %>
<ul id="nav">
    <li>Switch:</li>
    <li><%= link_to "Man", man_path, :title => "Never trust a man...", :class => "man" %></li>
    <li><%= link_to "Woman", woman_path, :title => "Never trust a woman...", :class => "woman" %></li>
</ul>

app/views/layouts/_pull.html.erb
<%= @fetch.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Never Trust A <%= @gender.capitalize %> Who...</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
</head>
<body id="<%= @gender %>">

<div id="wrap">
    <%= render 'layouts/header' %>
    <div id="content">
        <%= yield %>
    </div>
</div>

</body>
</html>